### ISSUE TITLE
Support AsyncAPI spec v2.6.0

### ISSUE THREAD

**Issue by ivan-penchev** [asyncapi/parser-go#190]
#### Reason/Context
Please try answering few of those questions
- Gives options to all people using Go to be able to parse AsyncAPI.
-  Wider adoption of language support, will bring wider adoption of the spec.

#### Description
[https://www.asyncapi.com/blog/release-notes-2.6.0](https://www.asyncapi.com/blog/release-notes-2.6.0)

**Comment by smoya** [comment]
Hi @ivan-penchev. Thanks for the report!

I was expecting `dependabot` to update the dependency but it is not possible because there was new major releases and manual changes are needed in this package.

I created a fix for the major release package for the schemas in https://github.com/asyncapi/spec-json-schemas/pull/377.
After being merged, I will create a new PR updating the dependency to the new major release.

**Comment by ivan-penchev** [comment]
Hey @smoya I could see that the changes you did were merged, but dependabot still hasn't updated here :)
